### ISSUE TITLE
PR 확인 후 피드백 및 담당자 확인

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/next-student-council-frontend#56]
1. 메인 페이지 @sy-paik 
![image](https://github.com/EveryUniv/next-student-council-frontend/assets/68864422/a20307a4-23e0-42a1-ad03-47bdff534550)

2. 하단 네비
이건 담당자가 누구인가요?

3. 로그인, 회원가입는 원래 담당자가 누군가요?

4. ID/PW 찾기는 아직 구현안된건가요? @sy-paik

**Comment by developerChans** [comment]
#53 이후 진행한 피드백

**Comment by developerChans** [comment]
![image](https://github.com/EveryUniv/next-student-council-frontend/assets/68864422/9fad1a4c-ddbd-428b-bfcb-199aedc8c4ea)

**Comment by sy-paik** [comment]
Gnh 컴포넌트와 DefaultLayout 의 전체적인 리팩토링 진행중입니다 후에 PR 올리겠습니다. 아이디 비밀번호 찾기는 현재 SMS 로직에 오류가 있어 API 수정되면 통신 후에 올리겠습니다
